services:
#  mongodb1:
#    container_name: mongodb1
#    image: dh-mirror.gitverse.ru/mongo:latest
#    volumes:
#      - mongodb1_data_container:/data/db
  # name: mongo-sharding

  mng_shard1_1:
    container_name: mng_shard1_1

    image: mongo:latest
    networks:
     pymongo-network:
        ipv4_address: 173.16.0.11
    ports:
      - "27011:27011"
    volumes:
      - mng_shard1_1_data:/data/db
    restart: always
    command:
      [
        "--shardsvr",
        "--replSet",  "rs1",
        "--bind_ip_all",
        "--port",  "27011"
      ]

  mng_shard2_1:
    container_name: mng_shard2_1
    image: mongo:latest
    networks:
      pymongo-network:
        ipv4_address: 173.16.0.21
    ports:
      - "27021:27021"
    volumes:
      - mng_shard2_1_data:/data/db
    restart: always
    command:
      [
        "--shardsvr",
        "--replSet",  "rs2",
        "--bind_ip_all",
        "--port",  "27021"
      ]

  mng_config1:
    container_name: mng_config1
    image: mongo:latest
    networks:
      pymongo-network:
        ipv4_address: 173.16.0.18
    ports:
      - "27018:27018"
    volumes:
      - mng_config1_data:/data/db
    restart: always
    command:
      [
        "--configsvr",
        "--replSet", "config_server",
        "--bind_ip_all",
        "--port", "27018"
      ]

  mng_router1:
    container_name: mng_router1
    image: mongo:latest
    depends_on:
      - mng_config1
    networks:
      pymongo-network:
        ipv4_address: 173.16.0.17
    ports:
      - "27017:27017"
    restart: always
    command:
      [
        "mongos",
        "--configdb", "config_server/mng_config1:27018",
        "--bind_ip_all",
        "--port", "27017"
      ]

  pymongo_api:
    container_name: pymongo_api
    build: 
      context: api_app
      dockerfile: api_app/Dockerfile
    image: kazhem/pymongo_api:1.0.0
    depends_on:
      - mng_router1
    networks:
      pymongo-network:
        ipv4_address: 173.16.0.80
    ports:
      - 8080:8080
    environment:
      MONGODB_URL: "mongodb://mng_router1:27017"
      MONGODB_DATABASE_NAME: "somedb"


networks:
  pymongo-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.16.0.0/16


volumes:
  mongodb1_data_container:
  mng_config1_data:
  mng_shard1_1_data:
  mng_shard2_1_data: